### ISSUE TITLE
AI-Based Content Filtering for Movies using Audio Recognition

### ISSUE THREAD

**Issue by mahmouds12** [alganzory/HaramBlur#34]
Many people enjoy watching videos and movies, but often encounter inappropriate content, such as nudity, kissing, explicit scenes, or offensive language. I propose two solutions:

- Develop or train a model that can recognize and filter out swear words in the **audio**, muting or beeping them.
- Create or train a model to detect inappropriate content in the **audio** accompanying nudity, kissing, explicit scenes, and mute or beep the audio, while also blurring the video.

Also, in the future, would we be able to add this to Smart TVs? it would be a great move if it's possible.

**Comment by alganzory** [comment]
Thank you for the suggestion, filtering Haram audio content is a good idea and it's in fact in the long term plan of this project inshallah, 
on a side note, I would like to state something: 
- The purpose of this extension is mainly to allow users to watch or browse Halal content that contain some Haram content, not the other way round, so if a movie contains nudity, kissing, I am really not very sure that would be Halal to watch even if those scenes were cut or blurred out, however, you can use the extension however you like as I am not giving a Fatwa of what's Halal and what's Haram, I am just stating my vision for this project and how I think it should be used. 

As for smart TVs, I believe this extension should still work on chrome on smart tv's? if you can try and let me know that would be great, I appreciate your support and suggestions

**Comment by mahmouds12** [comment]
Yes, I understand that this is not the main purpose of the extension, but I was thinking about how to benefit the majority of Muslims who might not be very strong Muslims. They still watch some movies, and even if a movie is labeled as 13+ or something, you might still hear some offensive words or there might be a kiss scene or a scene on a beach... So, forcing them to stop watching might be an impossible mission, but helping them by cutting or blurring some parts might be be reasonable.

For smart TVs, I think most people don't use Chrome on Smart TVs but rather use apps like Youtube or any streaming apps on TV OS like Tizen or Android or webOS... So, do you think it might be technically possible in the future to achieve the same concept of the chrome extension but on the Smart TV app level?

I appreciate your hard and innovative work. Thank you!

**Comment by alganzory** [comment]
@mahmouds12 , yeah I believe we have different perspectives on this, I believe in a way, if the user is watching something Haram to begin with, making it less haram might actually make them never think about leaving it, I totally get what you're saying about reducing the harm but I am still not quite sure about this idea. Also from a technical standpoint, this extension should still work on movie or streaming sites (if they use a video tag not an iframe as that's not supported yet #3) 

As for TV apps, I have zero experience with those, but hey, you never know, maybe in the future inshallah

Appreciate you support bro

**Comment by man2machine** [comment]
I agree with @alganzory

We should be encouraging the ummah to avoid haram content in the first place, and educating that it is actually haram. In my personal experience, a lot of people actually are not educated or simply ignore/forget what Islam considers as haram for lowering of the gaze.

I find this extension and other extensions like tahir to be beneficial to avoid corner cases where I have already tried to make my online experience halal, but because of the nature of the internet, sometimes something haram might show up inadvertently.

Another thing to note, is that AI detection based systems like the one in this extension will always be imperfect. There will always be some corner cases where it does not blur, even if we used a good algorithm that works most of the time. So we cannot fully rely on this, and instead we must be able to lower our gaze ourselves.
