### ISSUE TITLE
feature: Community knowledge base 

### ISSUE THREAD

**Issue by marwenbk** [alganzory/HaramBlur#35]
suggestion: why should each client process every asset? we can gather knowledge to check for quick verification, and when a client sees a new image his device does the work and sends the result.
It can also be a DNS server. Or a distributed ledger ( blockchain ) as a source of truth to avoid centralization?
with this strategy, we can cluster the load to be able to classify content with high-accuracy models
What do you think?

**Comment by man2machine** [comment]
Salam!

I'm not the creator of this extension, but I am one of its users that is following its development from a detection/AI standpoint. So my understanding does not represent the views of the developer @alganzory 

The sheer number of images on the internet is on the order of trillions. There is no way that such a large amount of image content can be stored to cache the detection results. New images would appear every day, people have different device screen sizes, there are thousands of frames in video, etc. There are many factors contributing to the huge number of images. This is not generally how machine-learning based image recognition works.

Furthermore, running a server that can store the detection results from each client so that it can be re-used later in other clients (or the same client), would also require additional resources (that would need to be payed for), which is outside of the extensions running on each client browser.

**Comment by marwenbk** [comment]
well i just wanted to share my thoughts. you guys knows better of course
