### ISSUE TITLE
Bug: Blurry start mode still noticeable

### ISSUE THREAD

**Issue by supfiger** [alganzory/HaramBlur#67]
Problems:

1. The settings that I have chosen are not always saved.
2. The settings that I have chosen are saved, but not all (or not correctly).
3. The settings are applied (blurring works), and then the blurring disappears.

**Video demonstration:**
https://monosnap.com/file/8lCQQJJrX1KaHBV9xpGolGgkjvKfEE

**Comment by alganzory** [comment]
Hi @supfiger, 

Thanks for your feedback
1 and 2:  You need to be on some tab (not a new tab) for your settings to be saved, in your video you were initially on a new tab where settings wouldn't be saved, but once you went to google search your settings were being saved just alright
3. The blurring disappears momentarily then reappears because of the blur on load feature that starts all media blurred until it's detected, however I do agree it shouldn't be noticeable so I'll work on that.  I am curious if you turned this setting on yourself and if you have tried without it?
