### ISSUE TITLE
Add google meets support

### ISSUE THREAD

**Issue by yayashn** [alganzory/HaramBlur#86]
At work I have to be in meetings, with my camera on & watch someone share their screen to outline goals.

Unfortunately there's always women there, so it would be very convenient if this can detect live google meets videos.

**Comment by yayashn** [comment]
If @alganzory or any contributor can give a high level overview on how to achieve this I can contribute to this feature inshaallah.

**Comment by alganzory** [comment]
Basically there's an if condition there that skips elements that have no 'src' attribute, if you comment it out, your google meet video will get scanned, but I can't just remove that if statement because I probably added it there for a reason that I can't quite recall at the moment 😅, I'll try to see if I can remove that condition but that will need some testing for edge cases that I, again, don't quite remember at the moment, if you wanna do some testing on that please let me know what you find

**Comment by yayashn** [comment]
> Basically there's an if condition there that skips elements that have no 'src' attribute, if you comment it out, your google meet video will get scanned, but I can't just remove that if statement because I probably added it there for a reason that I can't quite recall at the moment 😅, I'll try to see if I can remove that condition but that will need some testing for edge cases that I, again, don't quite remember at the moment, if you wanna do some testing on that please let me know what you find

Thanks for the information @alganzory I'll have a look once I have some time, for the sake of compatibility could we just add a whitelist? e.g

```js
//pseudocode
const isInWhitelist = () => {
   window.location.href.includes(['meets.google.com'])
}

if (isInWhitelist() || element.src) {
...
}
```

**Comment by yayashn** [comment]
https://github.com/alganzory/HaramBlur/issues/86
